PackageIdentifier: ThemisDB.ThemisDB
PackageVersion: 1.0.0
Installers:
- Architecture: x64
  InstallerType: zip
  InstallerUrl: https://github.com/makr-code/ThemisDB/releases/download/v1.0.0/themisdb-1.0.0-win64.zip
  InstallerSha256: <HASH_PLACEHOLDER>
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin\themis_server.exe
    PortableCommandAlias: themis_server
ManifestType: installer
ManifestVersion: 1.6.0
